name: telegram message
on: [push]
jobs:

  build:
    name: Notification
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🔥 ${{ github.actor }} created commit:
            📝 Commit message: ${{ github.event.commits[0].message }}
            
            💩 See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
      - name: send telegram sticker
        run: |
          curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendSticker \
            -d chat_id=${{ secrets.TELEGRAM_TO }} \
            -d sticker=CAACAgQAAxkDAAMfYkcvUZJcWd20HVCHniK1N6bc9UMAAkcYAAKm8XEeayFzmiCwAfsjBA \
